CREATE TABLE materias (
	id int(10) unsigned NOT NULL AUTO_INCREMENT,
	materia varchar(150) NOT NULL,
	hrs_teoricas int(10) DEFAULT NULL,
	hrs_practicas int(10) DEFAULT NULL,
	status boolean,
	PRIMARY KEY (id),
	created_at timestamp,
	updated_at timestamp
);
INSERT INTO materias (materia, hrs_teoricas, hrs_practicas, status)
VALUES
	('ingles', 2, 0, true),
	('algebra', 4, 0, true),
	('fisica', 4, 0, true),
	('quimica', 4, 2, true),
	('tics', 2, 4, true),
	('mantenimiento', 2, 2, true),
	('materia de primer semestre 1', 2, 0, true),
	('materia de primer semestre 2', 4, 0, true),
	('materia de primer semestre 3', 4, 0, true),
	('materia de primer semestre 4', 4, 2, true),
	('materia de primer semestre 5', 2, 4, true),
	('materia de primer semestre 6', 2, 2, true),
	('materia de segundo semestre 1', 2, 0, true),
	('materia de segundo semestre 2', 4, 0, true),
	('materia de segundo semestre 3', 4, 0, true),
	('materia de segundo semestre 4', 4, 2, true),
	('materia de segundo semestre 5', 2, 4, true),
	('materia de segundo semestre 6', 2, 2, true),
	('materia de tercer semestre 1', 2, 0, true),
	('materia de tercer semestre 2', 4, 0, true),
	('materia de tercer semestre 3', 4, 0, true),
	('materia de tercer semestre 4', 4, 2, true),
	('materia de tercer semestre 5', 2, 4, true),
	('materia de tercer semestre 6', 2, 2, true),
	('materia de cuarto semestre 1', 2, 0, true),
	('materia de cuarto semestre 2', 4, 0, true),
	('materia de cuarto semestre 3', 4, 0, true),
	('materia de cuarto semestre 4', 4, 2, true),
	('materia de cuarto semestre 5', 2, 4, true),
	('materia de cuarto semestre 6', 2, 2, true),
	('materia de quinto semestre 1', 2, 0, true),
	('materia de quinto semestre 2', 4, 0, true),
	('materia de quinto semestre 3', 4, 0, true),
	('materia de quinto semestre 4', 4, 2, true),
	('materia de quinto semestre 5', 2, 4, true),
	('materia de quinto semestre 6', 2, 2, true),
	('materia de sexto semestre 1', 2, 0, true),
	('materia de sexto semestre 2', 4, 0, true),
	('materia de sexto semestre 3', 4, 0, true),
	('materia de sexto semestre 4', 4, 2, true),
	('materia de sexto semestre 5', 2, 4, true),
	('materia de sexto semestre 6', 2, 2, true);